import{jsx as _jsx}from"react/jsx-runtime";import{addPropertyControls,ControlType}from"framer";/**
 * @framerDisableUnlink
 *
 * @framerIntrinsicWidth 240
 * @framerIntrinsicHeight 240
 *
 * @framerSupportedLayoutWidth any
 * @framerSupportedLayoutHeight any
 */function BlurGradient({blur,borderRadius,direction}){const getGradientDirection=direction=>{switch(direction){case"toBottom":return"to bottom";case"toTop":return"to top";case"toLeft":return"to left";case"toRight":return"to right";default:return"to bottom";}};const blurSteps=[{blur:`${blur/2/2/2/2/2/2/2}px`,gradient:`rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 1) 12.5%, rgba(0, 0, 0, 1) 25%, rgba(0, 0, 0, 0) 37.5%`},{blur:`${blur/2/2/2/2/2/2}px`,gradient:`rgba(0, 0, 0, 0) 12.5%, rgba(0, 0, 0, 1) 25%, rgba(0, 0, 0, 1) 37.5%, rgba(0, 0, 0, 0) 50%`},{blur:`${blur/2/2/2/2/2}px`,gradient:`rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 1) 37.5%, rgba(0, 0, 0, 1) 50%, rgba(0, 0, 0, 0) 62.5%`},{blur:`${blur/2/2/2/2}px`,gradient:`rgba(0, 0, 0, 0) 37.5%, rgba(0, 0, 0, 1) 50%, rgba(0, 0, 0, 1) 62.5%, rgba(0, 0, 0, 0) 75%`},{blur:`${blur/2/2/2}px`,gradient:`rgba(0, 0, 0, 0) 50%, rgba(0, 0, 0, 1) 62.5%, rgba(0, 0, 0, 1) 75%, rgba(0, 0, 0, 0) 87.5%`},{blur:`${blur/2/2}px`,gradient:`rgba(0, 0, 0, 0) 62.5%, rgba(0, 0, 0, 1) 75%, rgba(0, 0, 0, 1) 87.5%, rgba(0, 0, 0, 0) 100%`},{blur:`${blur/2}px`,gradient:`rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 1) 87.5%, rgba(0, 0, 0, 1) 100%`},{blur:`${blur}px`,gradient:`rgba(0, 0, 0, 0) 87.5%, rgba(0, 0, 0, 1) 100%`}];return /*#__PURE__*/_jsx("div",{style:{position:"relative",width:"100%",height:"100%",borderRadius:`${borderRadius}px`},children:blurSteps.map((step,index)=>/*#__PURE__*/_jsx("div",{style:{position:"absolute",inset:0,zIndex:index+1,backdropFilter:`blur(${step.blur})`,WebkitBackdropFilter:`blur(${step.blur})`,maskImage:`linear-gradient(${getGradientDirection(direction)}, ${step.gradient})`,WebkitMaskImage:`linear-gradient(${getGradientDirection(direction)}, ${step.gradient})`,borderRadius:`${borderRadius}px`,pointerEvents:"none"}},index))});}BlurGradient.defaultProps={blur:10,borderRadius:0,direction:"toBottom"};addPropertyControls(BlurGradient,{blur:{title:"Blur",type:ControlType.Number,defaultValue:10,min:0,max:100,step:1,description:"Large blur values (10<) can impact performance."},borderRadius:{title:"Radius",type:ControlType.Number,defaultValue:0,min:0,max:100,step:1,description:"Blur Gradient component's parent frame can't have border radius (it will break the component). If you need corner radius, apply it directly to the Blur Gradient component here."},direction:{title:"Direction",type:ControlType.SegmentedEnum,options:["toBottom","toTop","toLeft","toRight"],optionTitles:["↓","↑","←","→"],defaultValue:"toBottom"}});BlurGradient.displayName="Blur Gradient";export default BlurGradient;
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"BlurGradient","slots":[],"annotations":{"framerSupportedLayoutWidth":"any","framerIntrinsicHeight":"240","framerContractVersion":"1","framerIntrinsicWidth":"240","framerSupportedLayoutHeight":"any","framerDisableUnlink":"*"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./BlurGradient.map