// Interactive Frame with hover-reveal opacity effect
// Behaves like a native Framer Frame, with fill, border, shadow, radius, and interactive opacity mask
import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{useRef,useState,useEffect,startTransition}from"react";import{addPropertyControls,ControlType,useIsStaticRenderer}from"framer";// Global hover state
let globalHover={hovered:false,x:0,y:0,listeners:new Set};function notifyGlobalHover(){for(const fn of globalHover.listeners)typeof fn==="function"&&fn(globalHover);}function subscribeGlobalHover(fn){globalHover.listeners.add(fn);return()=>globalHover.listeners.delete(fn);}// Use a symbol to avoid polluting window with a string property
const FRAMER_FRAME_REVEAL_LISTENER=Symbol.for("__framerFrameRevealGlobalListener");if(typeof window!=="undefined"&&!window[FRAMER_FRAME_REVEAL_LISTENER]){window[FRAMER_FRAME_REVEAL_LISTENER]=true;window.addEventListener("mousemove",e=>{globalHover.hovered=true;globalHover.x=e.clientX;globalHover.y=e.clientY;notifyGlobalHover();});window.addEventListener("mouseout",e=>{globalHover.hovered=false;notifyGlobalHover();});}/**
 *
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerIntrinsicWidth 400
 * @framerIntrinsicHeight 200
 * @framerDisableUnlink
 */function FrameReveal(props){const{fill,border,borderWidth,borderColor,borderStyle,shadow,borderRadius,baseOpacity,hoverOpacity,range,style,children}=props;const ref=useRef(null);const[localHover,setLocalHover]=useState({hovered:false,x:0,y:0});const isStatic=useIsStaticRenderer();// Subscribe to global hover
useEffect(()=>{if(isStatic)return;function update(global){if(!ref.current)return;const rect=ref.current.getBoundingClientRect();// Check if the global cursor is within the reveal range of this frame
const cx=global.x-rect.left;const cy=global.y-rect.top;const inside=global.x>=rect.left&&global.x<=rect.right&&global.y>=rect.top&&global.y<=rect.bottom;// If cursor is within the reveal range of this frame, set hovered true
// But we want the mask to appear even if the cursor is NEAR the frame (within range)
const distX=Math.max(0,rect.left-global.x,global.x-rect.right);const distY=Math.max(0,rect.top-global.y,global.y-rect.bottom);const dist=Math.sqrt(distX*distX+distY*distY);const reveal=dist<=props.range;startTransition(()=>setLocalHover({hovered:global.hovered&&reveal,x:cx,y:cy}));}update(globalHover);const unsub=subscribeGlobalHover(update);return()=>{unsub();};},[props.range,isStatic]);// Compose border style
const borderStr=border?`${border.borderWidth}px ${border.borderStyle} ${border.borderColor}`:"none";const boxShadow=shadow?shadow:"none";const radius=borderRadius;// Mask for the top layer
const[showMask,setShowMask]=useState(false);const[topOpacity,setTopOpacity]=useState(0);// Animate opacity and mask removal
useEffect(()=>{if(isStatic)return;let timeout;if(localHover.hovered){setShowMask(true);startTransition(()=>setTopOpacity(hoverOpacity));}else{startTransition(()=>setTopOpacity(0));// Remove mask after transition
timeout=window.setTimeout(()=>{setShowMask(false);},250);}return()=>{if(timeout)clearTimeout(timeout);};},[localHover.hovered,hoverOpacity,isStatic]);const maskImage=!isStatic&&showMask?`radial-gradient(circle ${range}px at ${localHover.x}px ${localHover.y}px, black 0%, transparent 100%)`:undefined;return /*#__PURE__*/_jsxs("div",{ref:ref,style:{...style,position:"relative",width:"100%",height:"100%",overflow:"visible"},tabIndex:0,"aria-label":"Interactive Frame",children:[/*#__PURE__*/_jsx("div",{style:{width:"100%",height:"100%",position:"absolute",top:0,left:0,background:fill,border:borderStr,boxShadow,borderRadius:radius,opacity:baseOpacity,pointerEvents:"none",overflow:"hidden"},children:children}),/*#__PURE__*/_jsx("div",{style:{width:"100%",height:"100%",position:"absolute",top:0,left:0,background:fill,border:borderStr,boxShadow,borderRadius:radius,WebkitMaskImage:maskImage,maskImage:maskImage,WebkitMaskRepeat:"no-repeat",maskRepeat:"no-repeat",WebkitMaskSize:"100% 100%",maskSize:"100% 100%",opacity:topOpacity,transition:"opacity 0.25s cubic-bezier(0.4,0,0.2,1)",pointerEvents:"none",overflow:"hidden"},children:children})]});}FrameReveal.displayName="Frame Hover Reveal";addPropertyControls(FrameReveal,{fill:{type:ControlType.Color,title:"Fill",defaultValue:"#FFFFFF"},border:{type:ControlType.Border,title:"Border",defaultValue:{borderWidth:1,borderStyle:"solid",borderColor:"#EEEEEE"},optional:true},shadow:{type:ControlType.BoxShadow,title:"Shadow"},borderRadius:{type:ControlType.BorderRadius,title:"Radius",defaultValue:"4px"},baseOpacity:{type:ControlType.Number,title:"Base",defaultValue:0,min:0,max:1,step:.01,unit:""},hoverOpacity:{type:ControlType.Number,title:"Hover",defaultValue:1,min:0,max:1,step:.01,unit:""},range:{type:ControlType.Number,title:"Range",defaultValue:80,min:1,max:2e3,step:1,unit:"px",description:"More components at [Framer University](https://frameruni.link/cc)."}});export default FrameReveal;
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"FrameReveal","slots":[],"annotations":{"framerIntrinsicWidth":"400","framerSupportedLayoutWidth":"any-prefer-fixed","framerContractVersion":"1","framerSupportedLayoutHeight":"any-prefer-fixed","framerIntrinsicHeight":"200","framerDisableUnlink":""}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./FrameHoverReveal_Prod.map