alter table public.profiles
  add column if not exists preferences jsonb not null default '{
    "theme": "dark",
    "density": "comfortable",
    "home_page": "home",
    "notifications": true,
    "timezone": "America/Sao_Paulo"
  }'::jsonb;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.profiles'::regclass and conname = 'profiles_preferences_object_check'
  ) then
    alter table public.profiles
      add constraint profiles_preferences_object_check
      check (jsonb_typeof(preferences) = 'object');
  end if;
end $$;

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  module text not null default '',
  entity_type text not null default '',
  entity_id text not null default '',
  description text not null default '',
  old_value jsonb,
  new_value jsonb,
  ip_address inet,
  user_agent text not null default '',
  created_at timestamptz not null default now()
);

alter table public.activity_logs add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.activity_logs add column if not exists action text not null default '';
alter table public.activity_logs add column if not exists module text not null default '';
alter table public.activity_logs add column if not exists entity_type text not null default '';
alter table public.activity_logs add column if not exists entity_id text not null default '';
alter table public.activity_logs add column if not exists description text not null default '';
alter table public.activity_logs add column if not exists old_value jsonb;
alter table public.activity_logs add column if not exists new_value jsonb;
alter table public.activity_logs add column if not exists ip_address inet;
alter table public.activity_logs add column if not exists user_agent text not null default '';
alter table public.activity_logs add column if not exists created_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.activity_logs'::regclass and conname = 'activity_logs_action_required_check'
  ) then
    alter table public.activity_logs
      add constraint activity_logs_action_required_check
      check (length(trim(action)) > 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.activity_logs'::regclass and conname = 'activity_logs_json_shape_check'
  ) then
    alter table public.activity_logs
      add constraint activity_logs_json_shape_check
      check (
        (old_value is null or jsonb_typeof(old_value) in ('object', 'array', 'string', 'number', 'boolean'))
        and (new_value is null or jsonb_typeof(new_value) in ('object', 'array', 'string', 'number', 'boolean'))
      );
  end if;
end $$;

create index if not exists activity_logs_user_id_created_at_idx on public.activity_logs (user_id, created_at desc);
create index if not exists activity_logs_module_created_at_idx on public.activity_logs (module, created_at desc);
create index if not exists activity_logs_entity_idx on public.activity_logs (entity_type, entity_id);
create index if not exists activity_logs_created_at_idx on public.activity_logs (created_at desc);

alter table public.activity_logs enable row level security;

drop policy if exists "Users can read own activity and managers read all activity" on public.activity_logs;
drop policy if exists "Users can insert own activity logs" on public.activity_logs;
drop policy if exists "Managers can insert activity logs" on public.activity_logs;

create policy "Users can read own activity and managers read all activity"
  on public.activity_logs for select to authenticated
  using ((select auth.uid()) = user_id or public.can_manage_users());

create policy "Users can insert own activity logs"
  on public.activity_logs for insert to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Managers can insert activity logs"
  on public.activity_logs for insert to authenticated
  with check (public.can_manage_users());

revoke all privileges on table public.activity_logs from anon, authenticated;
grant select, insert on table public.activity_logs to authenticated;
grant usage, select on sequence public.activity_logs_id_seq to authenticated;
